%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version 1.3                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function dB0=Mag_EFmri4
%====================================
p.Equation='X * -0.000004 + Y * -0.000005 + Z * 0.000005 + Z.*X * 0.000002';
dB0t=MagSymbolic(p);
dB0=dB0t;
p=[];
%--------------------
end
