%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version 1.3                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [B1x, B1y, B1z, E1x, E1y, E1z, Pos]=Coil_EFMRI
%====================================
p.B1File='D:\MRiLab2\E1.MAT';
p.CoilID=1;
p.E1File='D:\MRiLab2\B1.MAT';
AttributeOpt={'linear','nearest','cubic'};
p.Interp=AttributeOpt{1};
p.PosX=0;
p.PosY=0;
p.PosZ=0;
[B1xt, B1yt, B1zt, E1xt, E1yt, E1zt, Post]=CoilUser(p);
B1x(:,:,:,p.CoilID)=B1xt;
B1y(:,:,:,p.CoilID)=B1yt;
B1z(:,:,:,p.CoilID)=B1zt;
E1x(:,:,:,p.CoilID)=E1xt;
E1y(:,:,:,p.CoilID)=E1yt;
E1z(:,:,:,p.CoilID)=E1zt;
Pos(p.CoilID,:)=Post;
p=[];
%--------------------
end
